# Generated by Django 5.2.8 on 2025-11-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesure',
            new_name='Dht11',
        ),
    ]
