# Generated by Django 5.2.8 on 2025-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_mesure_dht11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11',
            name='sensor_id',
            field=models.IntegerField(default=1),
        ),
    ]
